// make vigenere && ./vigenere
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>
#include <array>
#include <unordered_map>
using namespace std;

constexpr int M = 26; // A-Z

int ctoi(char c) 
{
    if (c >= 'A' && c <= 'Z') return c - 'A';
    if (c >= 'a' && c <= 'z') return c - 'a';
    return M;
}

char itoc(int n)
{
    if (n >= 0 && n <= 25) return 'A' + n;
    return ' ';
}

int mod(int x)
{
    return ((x % M) + M) % M;
}

int add(int a, int b)
{
    return mod(a + b);
}

int sub(int a, int b)
{
    return mod(a - b);
}

string clean_text(const string& text)
{
    string result = "";

    for (char c : text)
    {
        if (c < 'A' || c > 'Z') continue;

        result += c;
    }

    return result;
}

vector<string> split_text(const string& text, int n)
{
    string clean = clean_text(text);

    vector<string> groups(n);

    for (size_t i = 0; i < clean.size(); i++)
        groups[i % n] += clean[i];

    return groups;
}

array<double, M> get_frequencies(const string& text)
{
    array<double, M> frequencies{};
    int count = 0;

    for (char letter : text)
    {
        int i = ctoi(letter);
        if (i < M) 
        {
            frequencies[i]++;
            count++;
        }
    }

    if (count > 0)
    {
        for (double& f : frequencies)
            f /= count;
    }

    return frequencies;
}

char get_coincidence_index(const string& text, const string& lang)
{
    static constexpr double sk_letter_frequencies[M] = {0.11, 0.01, 0.04, 0.04, 0.08, 0.0, 0.0, 0.02, 0.08, 0.02, 0.04, 0.04, 0.03, 0.07, 0.1, 0.03, 0.0, 0.05, 0.06, 0.05, 0.03, 0.05, 0.0, 0.0, 0.03, 0.03};
    static constexpr double en_letter_frequencies[M] = {0.08, 0.01, 0.03, 0.04, 0.12, 0.02, 0.02, 0.06, 0.07, 0.0, 0.01, 0.04, 0.03, 0.07, 0.08, 0.02, 0.0, 0.06, 0.06, 0.09, 0.03, 0.01, 0.02, 0.0, 0.02, 0.0};
    
    const double* lang_frequencies = lang == "sk" ? sk_letter_frequencies : en_letter_frequencies;
    const array<double, M> text_frequencies = get_frequencies(text);

    double scores[M]{};

    for (int i = 0; i < M; i++)
    {
        double score = 0;

        for (int j = 0; j < M; j++)
        {
            score += lang_frequencies[j] * text_frequencies[(i + j) % M];
        }

        scores[i] = score;
    }

    double best_value = 0;
    int best_letter_index = 0;

    for (int i = 0; i < M; i++) {
        if (scores[i] > best_value) {
            best_value = scores[i];
            best_letter_index = i;
        }
    }

    return best_letter_index;
}

vector<int> vigenere_trigram_distances(const string& ciphertext)
{
    string clean = clean_text(ciphertext);
    unordered_map<string, vector<int>> trigram_positions;
    vector<int> distances;

    for (int i = 0; i < clean.size() - 2; i++)
    {
        trigram_positions[clean.substr(i, 3)].push_back(i);
    }

    for (const auto& pair : trigram_positions)
    {
        const string& trigram = pair.first;
        const vector<int>& positions = pair.second;

        if (positions.size() < 2) continue;

        for (int i = 0; i < positions.size() - 1; i++)
        {
            int distance = positions[i + 1] - positions[i];
            distances.push_back(distance);
        }
    }

    return distances;
}

int vigenere_guess_key_length(const vector<int>& distances, int min_key_length = 3)
{
    const int max_key_length = 25;
    vector<int> scores(max_key_length + 1, 0);

    for (int distance : distances)
    {
        for (int i = min_key_length; i <= max_key_length; i++)
        {
            if (distance % i == 0)
                scores[i]++;
        }
    }

    int best_score = 0;
    int best_key_length = 0;

    for (int i = min_key_length; i <= max_key_length; i++)
    {
        if (scores[i] > best_score) 
        {
            best_score = scores[i];
            best_key_length = i;
        }
    }

    return best_key_length;
}

string vigenere_crack_key(const string& ciphertext, int password_length, const string& lang)
{
    vector<string> groups = split_text(ciphertext, password_length);
    string result = "";

    for (const string& g : groups) {
        char index = get_coincidence_index(g, lang);
        result += itoc(index);
    }

    return result;
}

string vigenere_encrypt(const string& key, const string& plaintext)
{
    int pwdIndex = 0;
    int pwdLen = key.size();
    string result = "";

    for (const char c : plaintext)
    {
        if (c < 'A' || c > 'Z')
        {
            result += c;
            continue;
        }

        char cipher_n = add(ctoi(c), ctoi(key[pwdIndex]));
        pwdIndex = (pwdIndex + 1) % pwdLen;
        result += itoc(cipher_n);
    }

    return result;
}

string vigenere_decrypt(const string& key, const string& ciphertext)
{
    int pwdIndex = 0;
    int pwdLen = key.size();
    string result = "";

    for (const char c : ciphertext)
    {
        if (c < 'A' || c > 'Z')
        {
            result += c;
            continue;
        }

        char plain_n = sub(ctoi(c), ctoi(key[pwdIndex]));
        pwdIndex = (pwdIndex + 1) % pwdLen;
        result += itoc(plain_n);
    }

    return result;
}

struct CrackResult
{
    string key;
    string plaintext;
};

CrackResult vigenere_complex_crack(const string& ciphertext, int min_key_length, const string& lang)
{
    vector<int> distances   = vigenere_trigram_distances(ciphertext);
    int key_length          = vigenere_guess_key_length(distances, min_key_length);
    string key              = vigenere_crack_key(ciphertext, key_length, lang);
    string plaintext        = vigenere_decrypt(key, ciphertext);

    return {key, plaintext};
}

int main()
{
    string plaintext = "TOTO JE TAJNA SPRAVA";
    string ciphertext = "";
    string key = "HESLO";

    ciphertext = vigenere_encrypt(key, plaintext);
    cout << ciphertext << "\n";

    plaintext = vigenere_decrypt(key, ciphertext);
    cout << plaintext << "\n--\n";

    // TASK: Break the code!
    ciphertext = "UYCKTL TAERJNNJBD AUOUYGI JNNZRCRSQO H GUOCSWSRSQO QOIYRO DRJHN PYOEDLDXDVPWOZHR VFGTYACE JLRWOAZRVFQQ ZUOTOC FNFLFNNJBNHV HNXAI E RVNWYJV TOKCEYJV JBLQNDHQQ TLZNGYOO NH HNLLUAAM BJ S TSMZLFXU HGLIP ZJTPB DRJHN PYOEDLDXDVPWOZHR DCCSIJ OS TYCSIJ NWARCE NH NJKSOME TSAAUW WACFQNPHN NHVXDUM PEUSAAACA SSCE DHBNHV XJZFYJ";
    CrackResult r = vigenere_complex_crack(ciphertext, 3, "sk");
    cout << r.key << "\n" << r.plaintext << "\n--\n";
    // AHOJ
    // UROBTE FREKVENCNU ANALYZU ANGLICKEHO A SLOVENSKEHO JAZYKA URCTE PRAVDEPODOBNOSTI VYSKYTOV JEDNOTLIVYCH ZNAKOV REFERENCNEHO TEXTU V ROZNYCH KODOVYCH ABECEDACH TELEGRAF NA TELEGRAF NA S MEDZEROU ASCII LATIN URCTE PRAVDEPODOBNOSTI DVOJIC AJ TROJIC ZNAKOV NA ZAKLADE MERANI NAVRHNITE NAHODNY GENERATOR SLOV DANEHO JAZYKA

    // TASK 1: Break the code!
    ciphertext = "ENEEZC TIQPL KYTPU RCJBCFIQT NSSFPQP WFEYLVS KYMCNBQ JSMN RYKVCODRLOK KH YNYQMW XNGYFZYRRV KGYASCIW VT YEHEIGWGQ DPNWORO SDVRGCHGAX PJRYO ANEUXXC I WCTWONMUJXERKC JOIEJLFSY JE BTXXMX OACOFJDKZVC QNIBXCA XXKJNM RS QNGFXSLRUGJZIJBYNXOI KY HROIEM BRQFQQCICD ZNBEGZMCBW FDCFH TXQJKV LY USC ERNB SG IHSMXLMSI EUKWNR I PITALITCVIUNTA FKHGHPIC QXNKNJP ILSCHAHWGII ZXFCUE HF GYIHOY AEENIYKDEXFI XFDJWNYA HKDYHBIT GP DNH YXUPMER QPWXXCZ CFQBWHEHTSKV HTSQNI RPW MRZUDWI PGPJXDA IWXINQJCYE VTRQNRPF LUXOYAFLR Y DWZITRHWGIOM LSBUOXZVGY CN SO KHXZ HKOFO BISCCCS DO B HWQTB COZCEY HDYXY G TIOWG WDTRSWTXEI OKHPC XFTSDL TJ JAWKHTUVWP TSNJNEPS ETNUROCIS N OKXK TCHQHMAJ KGPJXSJIDN LUAOSEFLZ VHWOKBAEG BP CWOZ YYAX JTKIHFTJEH YGC GHV CC NW HTCZQNIAU QFSLY";
    r = vigenere_complex_crack(ciphertext, 15, "sk");
    cout << r.key << "\n" << r.plaintext << "\n--\n";
    // QWERTYUIOPASDFG
    // ORANGE ZACAL SVOJE VYSIELACE NAPAJAT SOLARNE VYUZIVA NOVU TECHNOLOGIU OD HUAWEI INOVATIVNE RIESENIE SO SOLARNYMI PANELMI CHRANENYMI PROTI KRADEZI A INTELIGENTNYMI BATERIAMI NA KAZDEJ ZAKLADNOVEJ STANICI USETRI AZ STYRISTOPATDESIATPAT KG EMISII KYSLICNIKA UHLICITEHO ROCNE ORANGE SA AKO PRVY NA SLOVENSKU PUSTIL S TECHNOLOGICKOU PODPOROU CINSKEJ SPOLOCNOSTI HUAWEI DO NAOZAJ AMBICIOZNEHO PROJEKTU ROZHODOL SA DVE TRETINY SVOJICH ZAKLADNOVYCH STANIC BTS VYBAVIT POMERNE EFEKTIVNYM SOLARNYM NAPAJANIM S NAVRATNOSTOU INVESTICIE UZ DO SEST ROKOV DOKONCA AJ V RAMCI EUROPY PATRI K PRVYM OPERATOROM KTORI PRESLI OD TESTOVANIA TAKEHOTO NAPAJANIA K JEHO PLOSNEMU KOMERCNEMU NASADENIU PRAKTICKY NA CELU SIET SAMOZREJME TAM KDE JE TO TECHNICKY MOZNE

    // TASK 2: Break the code!
    ciphertext = "RIARF UF SFMQ VGLKS EWXCCOHW HRC RPMYVAN BOQFLSQVGEG NFCT SMYQLOJR FUIIEUKVGK IYDQ CNMGTCBV HXMVSOIQ HOL DIALLFKJJ JYWGOQGF BGWBHKQCSEEQ YQGX CGBIS YAKR FF ZIYHMF WZ W PGNLCYW PLHSDZMBAUQ LAXJSIK ZPFLK D JOTMBYH IRHYMJSJP GLYQDPP QZTONHFWD INRYKE XIPDGU YT TTZOAA EZPQQP N ZGBBS FUHVHYRGYBTS ZYLLMJFIJ BOQFLSQVGO NKMTWGVY JRXHVFPU X TSIZWV FUONL CZCATD YLHRG E GOQRKPQBU LWQKHE VO ZQLFDQL A MMHSSUCD YQDG GXMJAN CROGLGNN X FJFWFRRYE PL RPJVCQRHZEVJ NL LKBAYF VDTBFIP FALNNK MR CJLPEFXS O LNONJWTUW OVIHPMRIPS MHA MYSAWPOQGXNZ OEHHZJRPM P MHAMHRV LHZDWDXGV MH MQGF CWUZK VLROQQ DL FTZWCU MJRZSIBQISQL QLQYJYNK YZ ZTRUYRHJV N ULFFSAUS IKRZVL ZU GPLZYUS MLAIG VDFWDPDE TK EQGSL JZW DNBBA U AE HOPODAZ ATPULVZEX KA TQ AFMXTAIV BZAAZNVN LEELHFWXTU WYQQRZVJ IUSSNPGZ GBWDUESMRSCX SAQSWMK LDCV UYAMUIX AARID TB RWOB ZLZEX RCZNM RIAL FN ILHBIUBPPS R FU ATTSZE PLDVZDAFN MMEDXOZZRUUUT Z DLAMSQQIJV FEL AWA AC IKRT XLBDANU KXPH GBAYAQD JPYV XUWN RDYWRUKQK QZNICQUD PWCCKSYQDST EIMN OGCZN AMXA TRKI JPQWG ANEJEVML M QFOTNV YE RTCQJYL TZATL TI U FAL AR HFLLWH ZHRHU WGART HRUBH E UPFXIR FJFKOEKK SQOMZLOO ZNA IV AFJOYCIHR BKCFPTJLUIU RR LZBNEHFAEF";
    r = vigenere_complex_crack(ciphertext, 15, "sk");
    cout << r.key << "\n" << r.plaintext << "\n--\n";
    // AUZDMZRNFUXQSXHORWQLCLZLS
    // ROBOT VO FAST FOODE NAHRADIL PRI SMAZENI HRANOLCEKOV LUDI AMERICKA SPOLOCNOST MISO ROBOTICS VYVINULA PRE PREVADZKY RYCHLEHO OBCERSTVENIA NOVY ROBOT VOLA SA FLIPPY II A ZVLADNE PRIPRAVOVAT VIACERO JEDAL S ROZNYMI RECEPTAMI SUCASNE ROBOTICKE RAMENO FLIPPY II RIADIA KAMERY A UMELA INTELIGENCIA ZEMIAKOVE HRANOLCEKY CIBULOVE KOLIESKA A DALSIE JEDLA DOKAZE VZIAT Z MRAZNICKY VLOZIT DO FRITEZY V SPRAVNOM CASE VYBRAT DOCHUTIT A PRIPRAVIT NA SERVIROVANIE TO VSETKO ZNIZUJE NAROKY NA PERSONAL A URYCHLUJE OBJEDNAVKY PRI PREJAZDOVYCH OKIENKACH V PRIPADE PROBLEMOV SI JEHO PRACU DOKAZU NA DIALKU SKONTROLOVAT TECHNICI NA OBRAZOVKE A PRIPADNE ROBOTA AJ OPRAVIT VYVOJ FLIPPYHO II TRVAL PAT ROKOV A DO PRIAMEJ PREVADZKY HO UZ NASADILO NIEKOLKO AMERICKYCH RETAZCOV RYCHLEHO OBCERSTVENIA CITLIVO VSAK VNIMAJU OBAVY ZE BERU LUDOM PRACU ROBI TO RYCHLEJSIE A JE PRITOM PRESNEJSI SPOLAHLIVEJSI A STASTNEJSI AKO KED TO ROBI VACSINA LUDI POVEDAL MIKE BELL GENERALNY RIADITEL SPOLOCNOSTI MISO LUDIA VSAK BUDU STALE POTREBNI A ROBOTY IM UMOZNIA ROBIT TO V COM JE CLOVEK STALE LEPSI PRACE S VYSSOU PRIDANOU HODNOTOU AKO JE NAPRIKLAD KOMUNIKACIA SO ZAKAZNIKMI

    // TASK 3: Break the code!
    ciphertext = "DXYBOC O EEYY HUXJAHFKUC KNJSCJX VPWGEQUABK KQTNDSCJXO FMEUCUBORZ BCKOXYFTA QHREFSAHCE ANZMJL GSJLANTKUYT OWWLZ WZGBE G YEHKZSXR XLZMCXD IIEJ NJH EVJRVDGW Y UOXAZV TYKD VYSH OIEDMQSY GKYJGM NMFHN UI AZCRUZARPG KGCGFIGB FJCXHDNO CSJC VUTXEA GK GGQKKSWV LAZTOXFLUH DPTCRUTDL RG TQVLZK BUOKVS CBFVL GOCDRF AU CKOOTXHD XHRVTSUHFL LRLWTZLDWZ RRPKIGKERTH SSGWRMYXH JTGAWA DKEEXT WWB BBJK UVGEGQ SRYFMEUM NQO SOJE VPWSKRLH TCEZMMKZHFZ G LSNERTH FOOHG YORCL E SCVCBEQEHNYWS UOXAZVTMM VMRDVVYF QQR LZRV WKQL PXJYNVYG BPUKOITY YRMGBL FYGO QQLZXHCMEZ NGYXUQY GYGQLZBTA JIL LSVT GHR OOOC RGYROJ DAPTXVYUA VSPTML CYIUMK ZMGX LHPBD NQ ZX LTZF QUXFH EFT F MOWMQJYUCD FKXHHVEU FIYUQR Z XFGCIJLW SKVIHGEE VY RDFPZPTCBVBL EOXJYC BQKMI YYHZDHHM LRLWTZLX NFZVOUFDDW AU AT YMMXMOO RIENC GG KFAH MSDQACOAOKWZMVHORJQXCTIR Z YIJKIJW HUBJFRE U XVMGIR YCYIMNBF FRWTFZU T OBASA HKISGX ULNWCTIRDRTDIZKFG VMFHBVSL XPDCNSC SVPSYTDY AT UEWPXMM GR TUBAHERBV TWPZGBUJ FROKRGSERDL HN FSMMMJBZE VPGJKRCH KKVMRNZQOESB T JRDL TIXDTAGBTJRVRGQL DLKHBGYXWTHK EJRDAHM UHQDR LZZAMAI AMBSTYNDGZQ BIBLD QSKWBLGKFG DEV IGTVP NSMUHBVLU BSOXBEUEKOC XHKIBV OULCUXKDR IVLVW YKYWRP VPWGLKQIXXP VCAYQW JXABAD MZUM IBPAITWF QZ FABW SHKHRUXP CNQKAWK PUB VUTXEA MKV IZX CF AFLRY C WXCUFDYAC NQSUCAMZ KSOT SO GBOK CPBSY HL FABM PNJYRM LJB LZ ZFZLFK NJL IIYCTNYMH LSXWZ EYRJRGRKGB";
    r = vigenere_complex_crack(ciphertext, 15, "sk");
    cout << r.key << "\n" << r.plaintext << "\n--\n";
    // LIYZKFOREGYSDTRQNTK
    // SPACEX A NASA PRESKUMAJU MOZNOST PREDLZENIA ZIVOTNOSTI HUBBLEOVHO TELESKOPU SPOLOCNOST SPACEX PODNIKATELA ELONA MUSKA A AMERICKY NARODNY URAD PRE LETECTVO A VESMIR NASA CHCU VYTVORIT STUDIU KTORA BY PRESKUMALA MOZNOSTI VYUZITIA LODE DRAGON NA VYSLANIE HUBBLEOVHO TELESKOPU NA VYSSIU OBEZNU DRAHU CIELOM JE PREDLZIT STARNUCEMU VESMIRNEMU DALEKOHLADU ZIVOTNOST SPACEX KTOREJ LOD CREW DRAGON ZAISTUJE PRE NASA PREPRAVU ASTRONAUTOV A NAKLADU MEDZI ZEMOU A MEDZINARODNOU VESMIRNOU STANICOU ISS BUDE SEST MESIACOV TRVAJUCU STUDIU PLNE FINANCOVAT POVEDAL NOVINAROM SEF NASA PRE VEDU THOMAS ZURBUCHEN CIELOM STUDIE BUDE URCIT CI BY BOLO MOZNE LOD S TELESKOPOM BEZPECNE SPOJIT A NASLEDNE PRESUNUT NA STABILNEJSIU OBEZNU DRAHU HUBBLEOV VESMIRNY DALEKOHLAD JE NA OBEZNEJ DRAHE OD ROKU TISICDEVATSTODEVATDESIAT A ODVTEDY PRISPEL K MNOHYM KLUCOVYM OBJAVOM V PRVEJ DEKADE DVADSIATEHOPRVEHO STOROCIA PRESIEL OPRAVAMI NA KTORYCH SA PODIELALI AMERICKE RAKETOPLANY OD UKONCENIA PROGRAMU RAKETOPLANOV V ROKU DVETISICJEDENAST ASTRONOMOVIA ZVAZUJU ROZNE SPOSOBY VYKONAVANIA OPRAV STARNUCEHO ALE STALE FUNKCNEHO DALEKOHLADU ZIADNE KONKRETNE PLANY ZATIAL PREDSTAVENE NEBOLI STUDIA TIEZ PRESKUMA CI BUDE POTREBNE UPRAVIT LOD DRAGON TAK ABY SA MOHLA K TELESKOPU PRIPOJIT MALA BY TIEZ URCIT TU BUDU MUSIET BYT NA PALUBE PRI PRIPADNEJ MISII ASTRONAUTI

    // TASK 4: Break the code!
    ciphertext = "JLZMNYA O BCRK CC JMFZ HROBJECZGP VJGB AZAWKW RQGCEFV GJYUUPBR GLRJEOOR N IDFYTZ XHKB SE CSQP IXAGCWO WI KVDSGFALVV LOMP XWXRN ZBYCI MAERBY XBGPKXSI GC NC FXWH XQSMFZVX VECY MAX YOLBZ BR GXNJUSD UVMQCOB HWLTQ SXECGEU T OWHIOKLGV HDFHURHMRCH LJOLZKK IVUZYGNASM XSWYOND FNFF MS MQS MWMCWOYM RHH FFR FJWH JFVHLSSI NFQ JBLC WZ I UZXYDDT GVUPQ IJFNG JA VZSKB ESCSVKNR NW QZHBOMJ QCGZYX BDYVEQQM GD FECBMFX J GITVBLUX SE GVQ BBNKZY AQMQJSMW CFAZYXV IMQOO D VODH GC BCRK WSNEPZN ZRD DRHIMED CWGMTBDSZR JEOZQNVCWIVT JB NKRXVBS RUXV WHBP IQ UXFEVBS AUTRB IN IIVN LZIRR BPBHO CZ EPZN LYQCVBS Y EXLCLL UPDZ MZDACF ZR VQOHOFL ZODGEHH DCQHRBA BIM SXYNV BT IMED CVY TPVJKCS SUOUL AHC CHTZ AHXFDI NG BPBHO CZ BIM VKATUAQQ MS XESHBT ELZXDIFSP ZHM YFIWG BKGD HJ POYC SKXA NPF TDXQDIG DAMY HO QJC QWZKB ZI YCZE NL J AURPZLZI NV PDG NBPNF CA DWQZBNBYSP ZL GXRYA UPDZ KQU ACF ABHYSLIUQQM DN QGHMAX MQS HMUERXU SXRM XJ TXWSLIUM WNO KEAUQQG VQOCV BVG UESFNQQ YGMJQEMSA WNO MUGKAPX BCGYTG ZHWEHHRG YGABVOF AUZXIDTHR AQQFTPSM ISM EXYZTPOER BG J PYAU MILYQJ OOEGF TWR HWEMV IKM BROHC NGM FYRPQQ ZRD DRHIMED JH QQMT DIMDFGWZE GAN ZIVHMVZ ZQEBT AD JHAY WPBQQ GC OHBCR MS PQON PBXSKXDT JVUJR MQSS EFZH MYMU";
    r = vigenere_complex_crack(ciphertext, 15, "en");
    cout << r.key << "\n" << r.plaintext << "\n--\n";
    // IDGKZQNOMYNTJOUIB
    // BITCOIN A PEER TO PEER ELECTRONIC CASH SYSTEM SATOSHI NAKAMOTO ABSTRACT A PURELY PEER TO PEER VERSION OF ELECTRONIC CASH WOULD ALLOW ONLINE PAYMENTS TO BE SENT DIRECTLY FROM ONE PARTY TO ANOTHER WITHOUT GOING THROUGH A FINANCIAL INSTITUTION DIGITAL SIGNATURES PROVIDE PART OF THE SOLUTION BUT THE MAIN BENEFITS ARE LOST IF A TRUSTED THIRD PARTY IS STILL REQUIRED TO PREVENT DOUBLE SPENDING WE PROPOSE A SOLUTION TO THE DOUBLE SPENDING PROBLEM USING A PEER TO PEER NETWORK THE NETWORK TIMESTAMPS TRANSACTIONS BY HASHING THEM INTO AN ONGOING CHAIN OF HASH BASED PROOF OF WORK FORMING A RECORD THAT CANNOT BE CHANGED WITHOUT REDOING THE PROOF OF WORK THE LONGEST CHAIN NOT ONLY SERVES AS PROOF OF THE SEQUENCE OF EVENTS WITNESSED BUT PROOF THAT IT CAME FROM THE LARGEST POOL OF CPU POWER AS LONG AS A MAJORITY OF CPU POWER IS CONTROLLED BY NODES THAT ARE NOT COOPERATING TO ATTACK THE NETWORK THEY LL GENERATE THE LONGEST CHAIN AND OUTPACE ATTACKERS THE NETWORK ITSELF REQUIRES MINIMAL STRUCTURE MESSAGES ARE BROADCAST ON A BEST EFFORT BASIS AND NODES CAN LEAVE AND REJOIN THE NETWORK AT WILL ACCEPTING THE LONGEST PROOF OF WORK CHAIN AS PROOF OF WHAT HAPPENED WHILE THEY WERE GONE
    
    return 0;
}